name: build docker image

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  DOCKER_REPO: ghcr.io/hillnz/docker-nas-plex-dvr

jobs:

  build_images:

    strategy:
      matrix:
        include:
          - box: ubuntu-latest
            arch: x64
            platform: amd64
          - box: self-hosted
            arch: ARM64
            platform: arm64
            
    runs-on:
      - ${{ matrix.box }}
      - linux
      - ${{ matrix.arch }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/${{ matrix.platform }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max          
          tags: "${{ env.DOCKER_REPO }}/linux/${{ matrix.platform }}:${{ github.run_number }}"

  combine_images:
    runs-on: ubuntu-latest

    needs: [build_images]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to ghcr
        uses: docker/login-action@v1
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare dockerfile
        run: |
          echo "ARG TARGETPLATFORM\nFROM ${{ env.DOCKER_REPO }}/$TARGETPLATFORM:${{ github.run_number }}" >Dockerfile.multi

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile.multi
          platforms: linux/amd64,linux/arm64
          push: true
          tags: "${{ env.DOCKER_REPO }}:${{ github.run_number }}"
